/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tfnrc_rtp_codec_h264_NativeH264Decoder */

#ifndef _Included_edu_tfnrc_rtp_codec_h264_NativeH264Decoder
#define _Included_edu_tfnrc_rtp_codec_h264_NativeH264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_tfnrc_rtp_codec_h264_NativeH264Decoder
 * Method:    initDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_tfnrc_rtp_codec_h264_NativeH264Decoder_initDecoder
  (JNIEnv *, jclass);

/*
 * Class:     edu_tfnrc_rtp_codec_h264_NativeH264Decoder
 * Method:    DeinitDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_tfnrc_rtp_codec_h264_NativeH264Decoder_DeinitDecoder
  (JNIEnv *, jclass);

/*
 * Class:     edu_tfnrc_rtp_codec_h264_NativeH264Decoder
 * Method:    DecodeAndConvert
 * Signature: ([B[I)I
 */
JNIEXPORT jint JNICALL Java_edu_tfnrc_rtp_codec_h264_NativeH264Decoder_DecodeAndConvert
  (JNIEnv *, jclass, jbyteArray, jintArray);

/*
 * Class:     edu_tfnrc_rtp_codec_h264_NativeH264Decoder
 * Method:    getVideoWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_tfnrc_rtp_codec_h264_NativeH264Decoder_getVideoWidth
  (JNIEnv *, jclass);

/*
 * Class:     edu_tfnrc_rtp_codec_h264_NativeH264Decoder
 * Method:    getVideoHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_tfnrc_rtp_codec_h264_NativeH264Decoder_getVideoHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
